// Bold fields on screen; copy actions always use the unformatted prompt text.
function highlightPrompt(text,fields){
  const values=fields||[...text.matchAll(/\[[^\]\n]+\]/g)].map(m=>m[0]);
  if(!values.length)return esc(text);
  const escaped=[...new Set(values)].sort((a,b)=>b.length-a.length).map(s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));
  const re=new RegExp(escaped.join('|'),'g');let result='',last=0;
  for(const match of text.matchAll(re)){result+=esc(text.slice(last,match.index))+`<strong class="customize-field">${esc(match[0])}</strong>`;last=match.index+match[0].length;}
  return result+esc(text.slice(last));
}
function articleLinks(ids,location=''){
  return `<div class="article-links">${ids.map(id=>{const a=ARTICLES[id];return `<div><span class="study-tag">${esc(a.design)}</span><p>${ext(a.url,a.short+' · Read on JOP')}</p></div>`;}).join('')}${location?`<p class="note source-location"><strong>Source location:</strong> ${esc(location)}</p>`:''}</div>`;
}
function renderArticles(){
  setPage(`${pageIntro('Published examples','Learn from five JOP publications.','See how to plan, write, and present research using details from five published studies. Each paper links directly to its Journal of Prosthodontics page.')}<div class="notice">${esc(EXAMPLE_NOTE)} PDF page references refer to the author-supplied versions; journal pagination may change after Early View.</div><div class="article-catalog">${Object.entries(ARTICLES).map(([id,a])=>`<article class="panel publication-card" id="article-${id}"><span class="study-tag">${esc(a.design)}</span><h2>${esc(a.title)}</h2><p class="note">${esc(a.citation)} DOI: ${esc(a.doi)}</p><p>${esc(a.takeaway)}</p>${ext(a.url,'Read the publication on JOP')}<details><summary>Verified facts used in the examples</summary><p>${esc(a.facts)}</p><p class="note">${esc(a.location)}</p></details><div class="row wrap publication-lessons">${a.modules.map(id=>`<a class="button secondary" href="#lesson/${id}">${esc(MODULES.find(m=>m.id===id).short)}</a>`).join('')}</div></article>`).join('')}</div><p class="note">The site provides original summaries and links. Published articles and figures retain their original rights. The examples do not imply that the authors used generative AI in their studies.</p>`,'Published examples','articles');
}
function renderAIResources(){
  $('#tool-content').innerHTML=`<section class="panel resource-start"><div class="eyebrow">AI resources for researchers</div><h2>From a question to a cited paragraph</h2><p>Choose a tool for a specific job, then carry verified information into the next step. The examples below use the same <a href="#articles">five JOP publications</a> as the lessons.</p><ol class="resource-workflow"><li><strong>Discover.</strong> Frame a focused question and collect candidate papers with Elicit, <strong>OpenEvidence</strong>, another appropriate clinical evidence tool, or a database search. Record the query and date.</li><li><strong>Read and verify.</strong> Use Gemini Notebook/NotebookLM or a source-based chat to extract methods and results. Open every supporting passage.</li><li><strong>Keep real citations.</strong> Save the verified journal or PubMed record in Zotero. Check title, authors, year, DOI, and claim support; a valid DOI alone does not prove the claim.</li><li><strong>Draft and audit.</strong> Give ChatGPT the checked facts and citation keys. Compare its paragraph with the evidence worksheet, then format references with the reference manager.</li></ol><p>${ext('https://pubmed.ncbi.nlm.nih.gov/','Open PubMed')} · ${ext('https://www.zotero.org/support/adding_items_to_zotero','Add verified records to Zotero')}</p><p class="note">PubMed and Zotero are useful non-LLM companions. For example, add DOI <strong>10.1111/jopr.70151</strong> with Zotero’s identifier tool, open the Xu record, and attach your checked notes before citing it in Word.</p></section><div class="notice"><strong>Tool information checked ${TOOL_REVIEW_DATE}.</strong> The toolkit includes Gemini Notebook/NotebookLM, ChatGPT, ChatGPT for Clinicians, <strong>OpenEvidence</strong>, and Elicit. This course is free; external services have their own accounts, eligibility rules, limits, and terms. ${esc(EXAMPLE_NOTE)} Copy a prompt into your chosen tool; this website does not run it.</div><div class="filter-group" id="resource-filters" aria-label="Filter AI resources">${['All','Read & extract','Write & analyze','Clinical evidence'].map((x,i)=>`<button class="filter" data-resource-filter="${x}" aria-pressed="${i===0}">${esc(x)}</button>`).join('')}</div><p class="note" id="resource-count" aria-live="polite"></p><div id="resource-grid" class="resource-list"></div><section class="panel"><h2>Keep the work moving</h2><p>Use the <a href="#toolkit/templates">Excel evidence worksheet</a> to retain verified claims and source locations. The <a href="#lesson/statistics">statistics</a>, <a href="#lesson/figures">figures</a>, and <a href="#lesson/conference">conference</a> modules provide complete prompts for code review, plotting, and presentations. Record each actual use in the <a href="#toolkit/disclosure">AI disclosure builder</a>.</p></section>`;
  function show(category){
    const items=AI_RESOURCES.filter(t=>category==='All'||t.category===category);
    $('#resource-grid').innerHTML=items.map(t=>`<article class="panel resource-card"><div class="eyebrow">${esc(t.category)}</div><h2>${esc(t.name)}</h2><p>${esc(t.description)}</p><p class="resource-access"><strong>Access:</strong> ${esc(t.access)}</p><p>${ext(t.url,'Open '+t.name)}</p><p class="note">Official information: ${t.sources.map(s=>ext(s[1],s[0])).join(' · ')}</p><h3>Try this workflow</h3><ol>${t.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><div class="prompt-header"><h3>1 · Make it yours</h3><button class="copy-button" data-resource-copy="${t.id}:template" aria-label="Copy ${esc(t.name)} template">${icon('copy')}Copy template</button></div><p class="customize-hint">Change the <strong>bold details</strong> to match your study.</p><pre class="prompt-text">${highlightPrompt(t.template)}</pre><section class="worked-example"><h3>${esc(t.example.title)}</h3><details open><summary>2 · Copy this complete prompt</summary><div class="worked-actions"><button class="copy-button" data-resource-copy="${t.id}:filled">${icon('copy')}Copy complete prompt</button></div><pre class="prompt-text filled-prompt">${highlightPrompt(t.example.filled,t.example.customize)}</pre></details><details open><summary>3 · See the response</summary><div class="worked-actions"><button class="copy-button" data-resource-copy="${t.id}:answer">${icon('copy')}Copy response</button></div><pre class="example-response">${esc(t.example.answer)}</pre></details><p class="example-verification"><strong>Before you use it:</strong> ${esc(t.example.verify)}</p>${articleLinks(t.example.articleIds)}<details class="source-details"><summary>Where to check the details</summary><p class="note">${esc(t.example.location)}</p></details></section></article>`).join('');
    $('#resource-count').textContent=`${items.length} of ${AI_RESOURCES.length} resources shown`;
    $$('[data-resource-copy]').forEach(b=>b.addEventListener('click',()=>{const [id,key]=b.dataset.resourceCopy.split(':');const t=AI_RESOURCES.find(x=>x.id===id);copyText(key==='template'?t.template:t.example[key]);}));
  }
  $('#resource-filters').addEventListener('click',e=>{const b=e.target.closest('[data-resource-filter]');if(!b)return;$$('[data-resource-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));show(b.dataset.resourceFilter);});
  show('All');
}
